// Makes the nature's compass more difficult to craft by requiring the now defunct biome finder compass from Biomes O' Plenty
recipes.addShaped(
	<naturescompass:naturescompass>,
	[
		[
			<ore:treeLeaves>,
			<ore:blockLog>,
			<ore:treeLeaves>
		],
		[
			<ore:blockLog>,
			<biomesoplenty:biome_finder>,
			<ore:blockLog>
		],
		[
			<ore:treeLeaves>,
			<ore:blockLog>,
			<ore:treeLeaves>
		]
	]
);
